//bcrypt es un paquete de js para encriptar datos
import bcrypt from 'bcryptjs';
 
const data = {
  users: [
    {
      nombre: 'admin',
      email: 'admin@gmail.com',
      password: bcrypt.hashSync('admin'),
      isAdmin: true,
    },
    {
      nombre: 'yosh',
      email: 'yosh@gmail.com',
      password: bcrypt.hashSync('admin'),
      isAdmin: false,
    },
  ],

  productos: [
    {
      nombre: 'Prensa de piernas',
      ficha: 'Prensa-de-piernas',
      categoria: 'maquinas gym',
      imagen: 'https://i.ibb.co/zQt03yY/1-maquinagym.jpg',
      precio: '540',
      disponibles: 15,
      marca: 'ANYTHING SPORTS',
      descripcion: 'Prensa de piernas y sentadillas ',
    },
    {
      nombre: 'equipo de entrenamiento AB',
      ficha: 'equipo-de-entrenamiento-AB',
      categoria: 'maquinas gym',
      imagen: 'https://i.ibb.co/n186J5h/2-maquinagym.jpg',
      precio: '270',
      disponibles: 5,
      marca: 'Fitlaya Fitness',
      descripcion: 'Máquina de nivel profesional AB/núcleo',
    },
    {
      nombre: 'banco de entrenamiento de fuerza ajustable',
      ficha: 'banco-de-entrenamiento-de-fuerza-ajustable',
      categoria: 'maquinas gym',
      imagen: 'https://i.ibb.co/g6JDND0/3-maquinagym.jpg',
      precio: '160',
      disponibles: 9,
      marca: 'FLYBIRD ',
      descripcion:
        'La capacidad de peso es de 800 libras: diseñado con un marco único',
    },
    {
      nombre: 'Equipo portátil de entrenamiento de fuerza',
      ficha: 'Equipo-portátil-de-entrenamiento-de-fuerza',
      categoria: 'maquinas gym',
      imagen: 'https://i.ibb.co/LQ8CgCn/4-maquinagym.jpg',
      precio: '120',
      disponibles: 3,
      marca: 'Nomadix Fitness',
      descripcion: 'Máxima tensión y máximos resultados',
    },
    {
      nombre: 'Camiseta sin mangas para hombre',
      ficha: 'Camiseta-sin-mangas-para-hombre',
      categoria: 'ropa gym',
      imagen: 'https://i.ibb.co/2WvQMTP/5-ropagym.jpg',
      precio: '16',
      disponibles: 17,
      marca: 'NELEUS',
      descripcion: 'El material ofrece la ventaja de ser transpirable',
    },
    {
      nombre: 'Pantalones cortos de correr',
      ficha: 'Pantalones-cortos-de-correr',
      categoria: 'ropa gym',
      imagen: 'https://i.ibb.co/HVZgSgk/71-FJHug-ELOS.jpg',
      precio: '18',
      disponibles: 13,
      marca: 'Surenow ',
      descripcion: 'La tela mejorada es ligera y transpirable',
    },
    {
      nombre: 'Conjunto de 2 piezas de entrenamiento mujer',
      ficha: 'Conjunto-de-2-piezas-de-entrenamiento-mujer',
      categoria: 'ropa gym',
      imagen: 'https://i.ibb.co/2WvQMTP/5-ropagym.jpg',
      precio: '25',
      disponibles: 24,
      marca: 'WodoWei ',
      descripcion: 'Conjunto de 2 piezas para mujer: material suave y cómodo',
    },
    {
      nombre: 'pantalones deportivos de yoga',
      ficha: 'pantalones-deportivos-de-yoga',
      categoria: 'ropa gym',
      imagen: 'https://i.ibb.co/2WvQMTP/5-ropagym.jpg',
      precio: '13',
      disponibles: 7,
      marca: 'GXIN',
      descripcion: 'Tela: 60% nailon + 35% poliéster + 5% elastano',
    },
    {
      nombre: 'Optimum Nutrition ZMA',
      ficha: 'Optimum-Nutrition-ZMA',
      categoria: 'suplementos',
      imagen: 'https://i.ibb.co/LkkbRZS/81m-Yc-Ho-X-GL.jpg',
      precio: '160',
      disponibles: 3,
      marca: 'Optimum Nutrition',
      descripcion: '10 mg de vitamina B6, 435 mg de magnesio, 28 mg de zinc',
    },
    {
      nombre: 'Suplemento multivitamínico Animal Pak',
      ficha: 'Suplemento-multivitamínico-Animal-Pak',
      categoria: 'suplementos',
      imagen: 'https://i.ibb.co/KxzgxYF/81-T4-CPd-Ozf-L.jpg',
      precio: '126',
      disponibles: 8,
      marca: 'Animal',
      descripcion:
        'Apoyo de recuperación e inmunológico: con un complejo de aminoácidos completo',
    },
    {
      nombre: 'Cellucor C4 Ultimate',
      ficha: 'Cellucor-C4-Ultimate',
      categoria: 'suplementos',
      imagen: 'https://i.ibb.co/z5BVXgr/81-Cy3-H1-Jx-KL-AC-SL1500.jpg',
      precio: '145',
      disponibles: 2,
      marca: 'Cellucor',
      descripcion:
        'C4 Ultimate Shred contiene ingredientes de primera calidad y una fórmula de alta intensidad',
    },
    {
      nombre: 'Gatorade Botella mezcladora sin BPA',
      ficha: 'Gatorade-Botella-mezcladora-sin-BPA',
      categoria: 'suplementos',
      imagen: 'https://i.ibb.co/r3Df2ts/916b8-Ai-C2s-L-AC-SL1500.jpg',
      precio: '23',
      disponibles: 5,
      marca: 'Gatorade',
      descripcion: 'Boquilla grande para beber/verter y taza abatible',
    },
  ],
};

export default data;
